// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentListItem } from "./AgentListItem";

/**
 * Response wrapper for list of agents
 */
export type AgentsListResponse = { agents: Array<AgentListItem>, };
