// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentModelOption } from "./AgentModelOption";

/**
 * Response for agent model selection endpoints.
 */
export type AgentModelOptionsResponse = { models: Array<AgentModelOption>, };
