// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentHeaderOverride } from "./AgentHeaderOverride";

/**
 * Response for agent create operation
 */
export type AgentCreateResponse = { id: string, created: boolean, header_overrides: Array<AgentHeaderOverride>, };
