// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for agent file put operation
 */
export type AgentFilePutResponse = { filename: string, saved: boolean, };
