// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for agent delete operation
 */
export type AgentDeleteResponse = { id: string, deleted: boolean, };
