// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentHeaderOverride } from "./AgentHeaderOverride";

/**
 * Response for agent update operation
 */
export type AgentUpdateResponse = { id: string, updated: Array<string>, header_overrides: Array<AgentHeaderOverride>, };
