// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for agent clone operation
 */
export type AgentCloneResponse = { id: string, created: boolean, files_cloned: bigint, errors: Array<string>, };
