// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent-selectable raw provider/model pair.
 */
export type AgentModelOption = { name: string, provider: string, model: string, description: string | null, };
