// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual cron run item
 */
export type CronRunItem = { id: string, job_id: string, scheduled_at: bigint, executed_at: bigint | null, completed_at: bigint | null, status: string, output_preview: string | null, error: string | null, duration_ms: bigint | null, };
