// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cron enhance response
 */
export type CronEnhanceResponse = { original: string, enhanced: string, };
