// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CronRunItem } from "./CronRunItem";

/**
 * Cron runs list response
 */
export type CronRunsListResponse = { runs: Array<CronRunItem>, };
