// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cron job delete response
 */
export type CronJobDeleteResponse = { deleted: boolean, job_id: string, };
