// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cron job create response
 */
export type CronJobCreateResponse = { job_id: string, name: string, agent_id: string, schedule: string, message: string, created_at: bigint, };
