// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cron job trigger response
 */
export type CronJobTriggerResponse = { triggered: boolean, job_id: string, job_name: string, agent_id: string, };
