// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual cron job item
 */
export type CronJobItem = { id: string, agent_id: string, name: string, schedule: string, message: string | null, kind: string, depends_on: Array<string> | null, max_retries: number | null, retry_delay_secs: bigint | null, retry_count: number, last_status: string | null, enabled: boolean, };
