// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CronJobItem } from "./CronJobItem";

/**
 * Cron job list response
 */
export type CronJobsListResponse = { jobs: Array<CronJobItem>, };
