// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dashboard session item for global sessions endpoint
 */
export type DashboardSessionItem = { id: string, agent_id: string, title: string | null, message_count: number, updated_at: bigint, };
