// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for device flow start endpoint
 */
export type DeviceFlowStartResponse = { device_code: string, user_code: string, verification_uri: string, interval: bigint, expires_in: bigint | null, };
