// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for device flow poll endpoint
 */
export type DeviceFlowPollResponse = { status: string, token: string | null, error: string | null, interval: bigint | null, };
