// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error response structure
 */
export type ErrorResponse = { error: string, id: string | null, agent_id: string | null, filename: string | null, allowed: Array<string> | null, };
