// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardSessionItem } from "./DashboardSessionItem";

/**
 * Response for global sessions list endpoint
 */
export type GlobalSessionsListResponse = { sessions: Array<DashboardSessionItem>, };
