// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for health endpoint
 */
export type HealthResponse = { status: string, version: string, uptime_secs: bigint, agents: number, };
