// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeartbeatStatusItem } from "./HeartbeatStatusItem";

/**
 * Response for heartbeat status endpoint
 */
export type HeartbeatStatusResponse = { agents: Array<HeartbeatStatusItem>, };
