// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual heartbeat status item
 */
export type HeartbeatStatusItem = { agent_id: string, enabled: boolean, health: string, last_tick: bigint | null, next_tick: bigint | null, interval_secs: bigint | null, message_preview: string | null, latest_session: string | null, };
