// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogTokens } from "./LogTokens";

/**
 * Log entry for agent logs
 */
export type LogEntry = { timestamp: bigint, level: string, agent: string, source: string, message: string, duration_ms: bigint | null, model: string, tool_calls: number, tokens: LogTokens, };
