// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogEntry } from "./LogEntry";

/**
 * Logs list response
 */
export type LogsListResponse = { logs: Array<LogEntry>, };
