// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token counts for log entry
 */
export type LogTokens = { prompt: bigint, completion: bigint, total: bigint, };
