// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for masked key endpoint
 */
export type MaskedKeyResponse = { provider: string, has_key: boolean, masked_key: string | null, env_var: string | null, };
