// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryItem } from "./MemoryItem";

/**
 * Response for memory list endpoint
 */
export type MemoryListResponse = { entries: Array<MemoryItem>, };
