// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for memory delete endpoint
 */
export type MemoryDeleteResponse = { deleted: boolean, key: string | null, };
