// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Memory item for list response
 */
export type MemoryItem = { key: string, value: string, tags: Array<string>, timestamp: string, score: number | null, };
