// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Model information for discovery responses
 */
export type ModelInfo = { id: string, name: string, provider: string, description: string | null, input_price: number | null, output_price: number | null, context_window: bigint | null, max_output: bigint | null, tool_call: boolean, reasoning: boolean, attachment: boolean, family: string | null, cache_read_price: number | null, cache_write_price: number | null, modalities: Array<string> | null, };
