// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for provider key clear/set operations
 */
export type ProviderSetKeyResponse = { ok: boolean, provider: string, };
