// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider status item in the list response
 */
export type ProviderStatusItem = { provider: string, name: string, configured: boolean, has_api_key: boolean, env_var: string | null, env_vars: Array<string>, details: string | null, source: string | null, api: string | null, model_count: number, };
