// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for provider auth save operation
 */
export type ProviderAuthResponse = { success: boolean, message: string, };
