// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReceiptItem } from "./ReceiptItem";

/**
 * Response for receipts list endpoint
 */
export type ReceiptsListResponse = { receipts: Array<ReceiptItem>, };
