// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnReceiptResponse } from "./TurnReceiptResponse";

/**
 * Response for receipt get endpoint
 */
export type ReceiptGetResponse = { file: string, receipts: Array<TurnReceiptResponse>, };
