// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionDiagnosticsModelCallTrace } from "./SessionDiagnosticsModelCallTrace";

/**
 * Lazy-loaded response for per-receipt model call traces.
 */
export type SessionDiagnosticsReceiptModelCallsResponse = { session_id: string, receipt_id: bigint, model_calls: Array<SessionDiagnosticsModelCallTrace>, };
