// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Receipt tool call record for session diagnostics.
 */
export type SessionDiagnosticsToolCallRecord = { tool: string, args_summary: string, success: boolean, duration_ms: bigint, error: string | null, };
