// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for session delete operation
 */
export type SessionDeleteResponse = { session_id: string, deleted: boolean, };
