// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session list item
 */
export type SessionItem = { file: string, session_id: string, agent_id: string, created_at: bigint, modified: bigint, title: string | null, message_count: number, };
