// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage summary for session diagnostics.
 */
export type SessionDiagnosticsTokenUsageSummary = { prompt_tokens: bigint, completion_tokens: bigint, total_tokens: bigint, cached_tokens: bigint, reasoning_tokens: bigint, };
