// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionDiagnosticsPromptSection } from "./SessionDiagnosticsPromptSection";
import type { SessionDiagnosticsPromptTool } from "./SessionDiagnosticsPromptTool";

/**
 * Structured prompt snapshot captured for a turn.
 */
export type SessionDiagnosticsPromptSnapshot = { sections: Array<SessionDiagnosticsPromptSection>, available_tools: Array<SessionDiagnosticsPromptTool>, };
