// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for getting current session
 */
export type SessionCurrentResponse = { session_id: string | null, };
