// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-model call detail for session diagnostics receipts.
 */
export type SessionDiagnosticsModelCallDetail = { call_index: number, model: string, provider: string, api_surface: string | null, request_kind: string | null, prompt_tokens: bigint, completion_tokens: bigint, cached_tokens: bigint, reasoning_tokens: bigint, cost_usd: number | null, latency_ms: bigint, };
