// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionDiagnosticsReasoningTextStatus } from "./SessionDiagnosticsReasoningTextStatus";

/**
 * Detailed lazy-loaded model call trace.
 */
export type SessionDiagnosticsModelCallTrace = { call_index: number, provider: string, model_id: string, api_surface: string | null, request_kind: string | null, started_at: bigint, latency_ms: bigint, normalized_messages: unknown[], normalized_tools: unknown[], reasoning_effort: string | null, function_call_mode: string | null, prompt_tokens: bigint, completion_tokens: bigint, cached_tokens: bigint, reasoning_tokens: bigint, cost_usd: number | null, reasoning_text: string | null, reasoning_text_status: SessionDiagnosticsReasoningTextStatus, };
