// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionDiagnosticsTurnReceipt } from "./SessionDiagnosticsTurnReceipt";

/**
 * Individual turn entry for session diagnostics.
 */
export type SessionDiagnosticsTurn = { id: string, exchange_id: bigint | null, timestamp: bigint, role: string, content: string, tool_calls: unknown[] | null, tool_call_id: string | null, turn_receipt: SessionDiagnosticsTurnReceipt | null, };
