// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionDiagnosticsModelCallDetail } from "./SessionDiagnosticsModelCallDetail";
import type { SessionDiagnosticsPromptSnapshot } from "./SessionDiagnosticsPromptSnapshot";
import type { SessionDiagnosticsTokenUsageSummary } from "./SessionDiagnosticsTokenUsageSummary";
import type { SessionDiagnosticsToolCallRecord } from "./SessionDiagnosticsToolCallRecord";
import type { TurnReceiptReasoningTextStatus } from "./TurnReceiptReasoningTextStatus";

/**
 * Turn receipt attached to a diagnostics turn.
 */
export type SessionDiagnosticsTurnReceipt = { receipt_id: bigint, agent: string, session: string | null, assistant_exchange_id: bigint | null, started_at: bigint, duration_ms: bigint, user_prompt: string, tool_calls: Array<SessionDiagnosticsToolCallRecord>, tokens: SessionDiagnosticsTokenUsageSummary, model_calls: number, reply_summary: string, model_id: string, estimated_cost_usd: number | null, call_details: Array<SessionDiagnosticsModelCallDetail>, has_model_call_traces: boolean, prompt_snapshot: SessionDiagnosticsPromptSnapshot | null, reasoning_text: string | null, reasoning_text_status: TurnReceiptReasoningTextStatus | null, };
