// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured prompt section captured for a turn.
 */
export type SessionDiagnosticsPromptSection = { key: string, title: string, content: string, truncated: boolean, original_char_count: number | null, note: string | null, };
