// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool exposed to the model for a turn.
 */
export type SessionDiagnosticsPromptTool = { name: string, description: string | null, };
