// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionDiagnosticsSession } from "./SessionDiagnosticsSession";
import type { SessionDiagnosticsSummary } from "./SessionDiagnosticsSummary";
import type { SessionDiagnosticsTurn } from "./SessionDiagnosticsTurn";

/**
 * Response for session diagnostics endpoint.
 */
export type SessionDiagnosticsResponse = { session: SessionDiagnosticsSession, summary: SessionDiagnosticsSummary, turns: Array<SessionDiagnosticsTurn>, };
