// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session metadata for the diagnostics endpoint.
 */
export type SessionDiagnosticsSession = { id: string, agent_id: string, title: string | null, message_count: number, updated_at: bigint, };
