// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit reasoning text visibility status for a model call.
 */
export type SessionDiagnosticsReasoningTextStatus = "captured" | "provider_did_not_expose";
