// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate summary for a session diagnostics response.
 */
export type SessionDiagnosticsSummary = { total_turns: number, assistant_turns: number, tool_call_count: number, total_tokens: bigint, reasoning_tokens: bigint, estimated_cost_usd: number, };
