// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionItem } from "./SessionItem";

/**
 * Response for listing sessions
 */
export type SessionsListResponse = { sessions: Array<SessionItem>, };
