// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for session update operation
 */
export type SessionUpdateResponse = { session_id: string, saved: boolean, count: number, };
