// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for skill get endpoint
 */
export type SkillGetResponse = { name: string, description: string, instructions: string, frontmatter: string | null, operator_managed: boolean | null, allowed_tools: string | null, reference_files: Array<string>, };
