// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Skill item for list response
 */
export type SkillItem = { name: string, description: string | null, has_skill: boolean, };
