// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillItem } from "./SkillItem";

/**
 * Response for skill list endpoint
 */
export type SkillListResponse = { skills: Array<SkillItem>, };
