// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for skill update endpoint
 */
export type SkillUpdateResponse = { name: string, updated: boolean, };
