// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandInfo } from "./CommandInfo";

/**
 * Response for slash commands endpoint
 */
export type SlashCommandsResponse = { commands: Array<CommandInfo>, };
