// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestAgentUsage } from "./TestAgentUsage";

/**
 * Response for agent test endpoint
 */
export type TestAgentResponse = { response: string, content: string | null, usage: TestAgentUsage | null, };
