// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Usage info for test agent response
 */
export type TestAgentUsage = { input_tokens: bigint, output_tokens: bigint, };
