// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Usage row for usage endpoint (from store::UsageBucket)
 */
export type UsageRow = { day: string, agent: string, model: string, turns: bigint, prompt_tokens: bigint, completion_tokens: bigint, cached_tokens: bigint, reasoning_tokens: bigint, total_tokens: bigint, estimated_cost_usd: number, };
