// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageRow } from "./UsageRow";

/**
 * Response for usage endpoint
 */
export type UsageResponse = { usage: Array<UsageRow>, total_cost_usd: number, total_turns: bigint, };
