// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for webhook config update
 */
export type WebhookConfigUpdateResponse = { agent_id: string, updated: boolean, };
