// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Webhook configuration for an agent
 */
export type WebhookConfig = { enabled: boolean, secret: string | null, event_types: Array<string>, url: string, };
