// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebhookDeliveryItem } from "./WebhookDeliveryItem";

/**
 * Response for webhook deliveries list endpoint
 */
export type WebhookDeliveriesResponse = { agent_id: string, deliveries: Array<WebhookDeliveryItem>, };
