// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual webhook delivery log entry
 */
export type WebhookDeliveryItem = { id: string, timestamp: bigint, event_type: string, status: string, status_code: number | null, error: string | null, duration_ms: bigint | null, payload_preview: string | null, };
