// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for webhook test endpoint
 */
export type WebhookTestResponse = { success: boolean, message: string, delivery_id: string | null, };
