// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for webhook config endpoint
 */
export type WebhookConfigResponse = { agent_id: string, enabled: boolean, secret: string | null, event_types: Array<string>, url: string, };
